---
title: "Litterature analysis"
author: "Nicolas Fortin St-Gelais"
date: "July 25, 2018"
output: github_document
---

Table 1: The number of publications in the different Web of knowledge categories with "water quality" keyword in the Topic field
(see  [Web of knowledge categories](http://mjl.clarivate.com/scope/scope_scie/))

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='figures/',
                      echo=TRUE, warning=FALSE, message=FALSE,fig.width=6, fig.height=6,fig.align = "center")

knitr::opts_knit$set(output.dir="reports")
```

```{r setup, include=F}

propKW<-function(kword,refs)
{
for(i in 1:nrow(refs))
{
  temp=grep(pattern = kword,refs[i,"AB"],perl = T)
  temp=grep(pattern = kword,refs[i,"AB"],perl = T)
  if(length(temp)==0)out[i]=0
  if(length(temp)!=0)out[i]=1
}
return(sum(out)/length(out))
}

library(kableExtra)
library(tidyr)
source("R/read.ISI.R")

fields=read.csv("data/DomISIfields.csv")
```

Table 1: The 15 most frequent keywords in each Web of knowledge categories

```{r dom table, echo=FALSE}
  kable(fields) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)





```

```{r kw table, echo=FALSE}


kwbyDom=cbind(1:15,
  AbsKwCounter("data/ISI/WQ_2017_ES")[1:15,1],
      AbsKwCounter("data/ISI/WQ_2017_WR")[1:15,1],
   AbsKwCounter("data/ISI/WQ_2017_Eng")[1:15,1],
  AbsKwCounter("data/ISI/WQ_2017_Geo")[1:15,1],
   AbsKwCounter("data/ISI/WQ_2017_Bio")[1:15,1],
   AbsKwCounter("data/ISI/WQ_2017_Eco")[1:15,1],
      AbsKwCounter("data/ISI/WQ_2017_PH")[1:15,1])

colnames(kwbyDom)=c("Ranks","ES","WR","Eng","Geo","Bio","Eco","PH")


kable(kwbyDom) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)



```